services:
  db:
    image: postgres:16
    container_name: examhub_db
    environment:
      POSTGRES_USER: examhub
      POSTGRES_PASSWORD: examhub
      POSTGRES_DB: examhub
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: